#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/postgres"
#    username: postgres
#    password: aEiou
spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: "jdbc:postgresql://ec2-34-193-117-204.compute-1.amazonaws.com:5432/d4161qjpa5ogd5?sslmode=require"
#    username: ksizfhgwrkxxrh
#    password: b7c93ab59079106a84c1461c117bd9e8c6ac5e2aeed79f07879f9c4d4fbb36c2